#!/usr/bin/env bash
# ==============================================================================
# Linux Server Administration Suite: Static Host Routing & Interface Setup
# Configures static host routing, persistent netplan rules, and interface metrics.
# ==============================================================================
set -euo pipefail

STATIC_IFACE="${STATIC_IFACE:-eth1}"
STATIC_IP="${STATIC_IP:-192.168.56.10/24}"
GATEWAY_IP="${GATEWAY_IP:-192.168.56.1}"
DNS_SERVERS="${DNS_SERVERS:-1.1.1.1,8.8.8.8}"
NETPLAN_FILE="/etc/netplan/60-static-diagnostics.yaml"

log_info() {
    echo -e "\033[0;32m[INFO]\033[0m $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_warn() {
    echo -e "\033[1;33m[WARN]\033[0m $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

log_error() {
    echo -e "\033[0;31m[ERROR]\033[0m $(date '+%Y-%m-%d %H:%M:%S') - $1" >&2
}

apply_netplan_config() {
    log_info "Writing Netplan static configuration to ${NETPLAN_FILE}..."
    mkdir -p "$(dirname "$NETPLAN_FILE")"

    cat <<EOF > "${NETPLAN_FILE}"
# Generated by Linux Server Administration & Network Diagnostic Suite
network:
  version: 2
  renderer: networkd
  ethernets:
    ${STATIC_IFACE}:
      addresses:
        - ${STATIC_IP}
      routes:
        - to: 192.168.56.0/24
          via: ${GATEWAY_IP}
          metric: 100
      nameservers:
        addresses: [${DNS_SERVERS}]
      dhcp4: false
      dhcp6: false
EOF

    chmod 600 "${NETPLAN_FILE}"
    log_info "Netplan config generated. Validating..."
    if command -v netplan >/dev/null 2>&1; then
        if [ "$(id -u)" -eq 0 ]; then
            netplan generate
            netplan apply || log_warn "netplan apply returned non-zero, interface might be managed by hypervisor/cloud-init."
        else
            log_warn "Running unprivileged; skipping direct 'netplan apply'."
        fi
    else
        log_warn "netplan command not available on this host. Falling back to 'ip' routing commands."
    fi
}

apply_iproute_fallback() {
    log_info "Applying static host routing rules via iproute2..."
    if command -v ip >/dev/null 2>&1 && [ "$(id -u)" -eq 0 ]; then
        # Check if interface exists
        if ip link show "${STATIC_IFACE}" >/dev/null 2>&1; then
            ip addr add "${STATIC_IP}" dev "${STATIC_IFACE}" 2>/dev/null || true
            ip link set "${STATIC_IFACE}" up
            ip route add 192.168.56.0/24 via "${GATEWAY_IP}" dev "${STATIC_IFACE}" metric 100 2>/dev/null || true
            log_info "Static route successfully applied to ${STATIC_IFACE}."
        else
            log_warn "Interface ${STATIC_IFACE} not present. Existing interfaces:"
            ip -brief link show
        fi
    else
        log_info "[DRY-RUN / UNPRIVILEGED] Routing rule: ip route add 192.168.56.0/24 via ${GATEWAY_IP}"
    fi
}

display_routing_table() {
    log_info "Current Kernel Routing Table:"
    if command -v ip >/dev/null 2>&1; then
        ip route show
    elif command -v netstat >/dev/null 2>&1; then
        netstat -rn
    else
        echo "No route inspection utility found."
    fi
}

main() {
    log_info "=== Initializing Static Host Routing & Interface Provisioning ==="
    if [ -d "/etc/netplan" ]; then
        apply_netplan_config
    else
        apply_iproute_fallback
    fi
    display_routing_table
    log_info "=== Network configuration complete ==="
}

main "$@"
